# Generated by Django 5.2.10 on 2026-01-13 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã sản phẩm')),
                ('name', models.CharField(max_length=200, verbose_name='Tên sản phẩm')),
                ('unit', models.CharField(choices=[('PCS', 'Piece'), ('PKT', 'Pack'), ('CTN', 'Carton'), ('BTL', 'Bottle'), ('CAN', 'Can'), ('KG', 'Kilogram')], max_length=10, verbose_name='Đơn vị tính')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Giá bán')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Tồn kho')),
            ],
            options={
                'verbose_name': 'Sản phẩm',
                'verbose_name_plural': 'Sản phẩm',
            },
        ),
        migrations.CreateModel(
            name='PurchaseReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Số lượng nhập')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Giá nhập')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Tổng tiền')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian nhập hàng')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_receipts', to='inventories.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Phiếu nhập',
                'verbose_name_plural': 'Phiếu nhập',
                'ordering': ['-datetime'],
            },
        ),
    ]
