# Generated by Django 5.2.10 on 2026-01-13 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày bán')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Tổng tiền')),
            ],
            options={
                'verbose_name': 'Hóa đơn',
                'verbose_name_plural': 'Hóa đơn',
            },
        ),
        migrations.CreateModel(
            name='InvoiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Số lượng')),
                ('price_at_sale', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Giá bán lúc đó')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Thành tiền')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='sales.invoice', verbose_name='Hóa đơn')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventories.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Chi tiết hóa đơn',
                'verbose_name_plural': 'Chi tiết hóa đơn',
            },
        ),
    ]
